
# Server Configuration
server:
    port: 8080
    
spring:
 data: 
  rest:
   defaultMediaType: application/json
  mongodb:
   uri: mongodb://wynats:atun3s@ds125574.mlab.com:25574/wynats
   database: wynats